export const project = [
  {
    id:1,
    thumb:require('./images/img_portfolio_pc01.JPG'),
    device:'PC',
    title:'아이나비',
    date:'2014.09 ~ 2014.11',
    work:['HTML', 'CSS'],
    link:'http://www.inavi.com/',
  },
  {
    id:2,
    thumb:require('./images/img_portfolio_mb01.JPG'),
    device:'MOBILE',
    title:'맘스클럽',
    date:'2014.10 ~ 2014.11',
    work:['HTML', 'CSS'],
    link:'https://www.moms-club.co.kr/',
  },
  {
    id:3,
    thumb:require('./images/img_portfolio_pc02.JPG'),
    device:'PC / Mobile',
    title:'코오롱',
    date:'2014.11 ~ 2015.01',
    work:['HTML', 'CSS', '웹접근성'],
    link:'https://www.kolon.com/main/main.do',
  },
  {
    id:4,
    thumb:require('./images/img_portfolio_mb03.JPG'),
    device:'MOBILE',
    title:'중국 CJ 쇼핑몰',
    date:'2015.01 ~ 2015.02',
    work:['HTML', 'CSS'],
    link:'javasript:;',
  },
  {
    id:6,
    thumb:require('./images/img_portfolio_pc01.JPG'),
    device:'PC',
    title:'두원공과대학교',
    date:'2015.03 ~ 2015.04',
    work:['웹접근성'],
    link:'http://www.doowon.ac.kr/main.do',
  },
  {
    id:7,
    thumb:require('./images/img_portfolio_pc01.JPG'),
    device:'PC',
    title:'HeBA_Core 쇼핑몰',
    date:'2015.05 ~ 2015.05',
    work:['HTML', 'CSS'],
    link:'javasript:;',
  },
  {
    id:8,
    thumb:require('./images/img_portfolio_respon01.JPG'),
    device:'ResponsiveWeb',
    title:'투자증권',
    date:'2015.05 ~ 2015.08',
    work:['HTML', 'CSS'],
    link:'https://m.nhqv.com/main/main',
  },
  {
    id:9,
    thumb:require('./images/img_portfolio_pc05.JPG'),
    device:'PC',
    title:'SM면세점 쇼핑몰',
    date:'2015.08 ~ 2015.10',
    work:['HTML', 'CSS'],
    link:'http://www.smdutyfree.com/fcm001.do?goTo=main',
  },
  {
    id:10,
    thumb:require('./images/img_portfolio_pc06.JPG'),
    device:'PC',
    title:'호스피스완화의료',
    date:'2015.10 ~ 2015.12',
    work:['HTML', 'CSS', '웹접근성'],
    link:'http://hospice.cancer.go.kr/index.do',
  },
  {
    id:11,
    thumb:require('./images/img_portfolio_pc07.JPG'),
    device:'PC',
    title:'LG전자',
    date:'2015.12 ~ 2016.06',
    work:['HTML', 'CSS'],
    link:'http://www.lge.co.kr/lgekor/main.do',
  },
  {
    id:12,
    thumb:require('./images/img_portfolio_pc08.JPG'),
    device:'PC',
    title:'미래에셋대우',
    date:'2016.09 ~ 2016.12',
    work:['HTML', 'CSS', '웹접근성'],
    link:'https://www.miraeassetdaewoo.com/',
  },
  {
    id:13,
    thumb:require('./images/img_portfolio_pc09.JPG'),
    device:'PC / Mobile',
    title:'현대아울렛',
    date:'2017.12 ~ 2017.03',
    work:['HTML', 'CSS', 'javascript'],
    link:'javascript:;',
  },
  {
    id:14,
    thumb:require('./images/img_portfolio_pc10.JPG'),
    device:'PC',
    title:'LG유플러스(Roaming)',
    date:'2017.03 ~ 2017.05',
    work:['HTML', 'CSS'],
    link:'http://www.uplus.co.kr/',
  },
  {
    id:15,
    thumb:require('./images/img_portfolio_pc11.JPG'),
    device:'PC / Mobile',
    title:'SBC 중소기업연수원',
    date:'2017.05 ~ 2017.08',
    work:['HTML', 'CSS', 'javascript', '웹접근성'],
    link:'http://sbti.sbc.or.kr:8111/sh_mai001_001.do',
  },
  {
    id:16,
    thumb:'준비중입니다',
    device:'ResponsiveWeb',
    title:'현대자동차',
    date:'2017.09 ~ 2017.10',
    work:['HTML', 'CSS'],
    link:'javascript:;',
  },
  {
    id:17,
    thumb:require('./images/img_portfolio_pc12.JPG'),
    device:'PC',
    title:'KEB 하나은행 기업뱅킹(운영)',
    date:'2017.11 ~ 2018.04',
    work:['HTML', 'CSS', '웹접근성'],
    link:'https://biz.kebhana.com/index.jsp',
  },
  {
    id:18,
    thumb:require('./images/img_portfolio_mb06.jpg'),
    device:'mobile',
    title:'삼성카드 앱(키즈곰곰, 아지냥이, 베이비스토리, 인생락서)(운영)',
    date:'2018.07 ~ 2020.01',
    work:['HTML', 'CSS', 'javascript'],
    link:'javascript:;',
  },
  {
    id:19,
    thumb:require('./images/img_portfolio_respon02.PNG'),
    device:'ResponsiveWeb',
    title:'제주항공',
    date:'2020.09 ~ 2020.12',
    work:['HTML', 'SCSS'],
    link:'https://www.jejuair.net/ko/main/base/index.do',
  },
  {
    id:20,
    thumb:'준비중입니다',
    device:'PC',
    title:'IFRS9(재개발)',
    date:'2021.10 ~ 2022.02',
    work:['HTML', 'CSS', 'javascript'],
    link:'javascript:;',
  },
  {
    id:21,
    thumb:require('./images/img_portfolio_pc13.PNG'),
    device:'PC / Mobile',
    title:'교보생명 모바일 통합',
    date:'2022.03 ~ 2022.09',
    work:['HTML', 'CSS'],
    link:'https://www.kyobo.com/',
  },
  {
    id:22,
    thumb:require('./images/img_portfolio_mb07.PNG'),
    device:'PC / Mobile',
    title:'애큐온캐피탈',
    date:'2022.10 ~ 2022.12',
    work:['HTML', 'CSS', 'javascript'],
    link:'https://m.acuoncapital.com/',
  },
  {
    id:23,
    thumb:'준비중입니다',
    device:'ResponsiveWeb',
    title:'KB스타플랫폼 고도화',
    date:'2023.01 ~ 2023.06',
    work:['HTML', 'SCSS', 'javascript'],
    link:'javascript:;',
  },
]